title:            Digital Freepen
description:      Of everything you can write about in a digital world
url:              digitalfreepen.com
signoff:          Rudi Chen
disqus_shortname: digitalfreepen
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-36059196-1


links:
  - name:         About
    url:          /about
  - name:         Writing
    url:          /
  - name:         Works
    url:          /works
  - name:         Resume
    url:          /files/documents/CV-RudiChen-Web-August2016.pdf

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
